### ISSUE TITLE
Connector doesn't work on iOS

### ISSUE THREAD

**Issue by eatsports** [AppsFlyerSDK/appsflyer-unity-adrevenue-plugin#15]
Hello, apparently MoPub got bought out by AppLovin and yesterday all MoPub repos got deleted from Cocoapods, and now this connector no longer works:
 [!] Unable to find a specification for `mopub-ios-sdk (~> 5.18.0)` depended upon by `AppsFlyer-AdRevenue-MoPub`
 That's the error i get when i try to install pods.
 Is there  any solution for this at the moment?

**Comment by tienhagioi** [comment]
Same issues .
I changed "AppsFlyer-AdRevenue-MoPub" to "AppsFlyer-AdRevenue" in pods and reinstall . 
Install and build success but logAdRevenue not work

**Comment by af-fess** [comment]
Hey @eatsports and @tienhagioi . We are working on deploying Android and iOS connectors before we update a Unity plugin. I believe it will be done tomorrow - the day after tomorrow. Thank you for the update.

**Comment by af-margot** [comment]
Hi @eatsports, @tienhagioi,

We are deprecating this connector and moving to [our generic connector](https://github.com/AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector) which does not contain Mopub.
